name: rosmol-ai-bot

services:
  certbot:
    profiles: ["tls"]
    image: certbot/certbot:v5.7.0@sha256:34ee91d2f43008eb78a007d22f23ed4b2eaa9a454cb27ca2c042b49527a695b4
    pull_policy: never
    platform: linux/amd64
    volumes:
      - ./data/private/letsencrypt:/etc/letsencrypt
      - ./data/private/acme-webroot:/var/www/certbot
