from __future__ import annotations

import re
import tomllib
from pathlib import Path

from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]
SHA256_REF = re.compile(r"@sha256:[0-9a-f]{64}(?:\s|$)")


def _read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def _input_requirements(path: str) -> set[str]:
    result: set[str] = set()
    for raw_line in _read(path).splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-r ")):
            continue
        result.add(str(Requirement(line)))
    return result


def _project_requirements(group: str | None = None) -> set[str]:
    config = tomllib.loads(_read("pyproject.toml"))
    if group is None:
        values = config["project"]["dependencies"]
    else:
        values = config["project"]["optional-dependencies"][group]
    return {str(Requirement(value)) for value in values}


def _assert_hashed_lock(path: str) -> None:
    text = _read(path)
    assert "autogenerated by pip-compile with Python 3.11" in text
    assert "--hash=sha256:" in text
    assert "# WARNING:" not in text

    starts = list(re.finditer(r"(?m)^(?P<name>[A-Za-z0-9_.-]+)==[^\s\\]+", text))
    assert starts, path
    for index, match in enumerate(starts):
        end = starts[index + 1].start() if index + 1 < len(starts) else len(text)
        assert "--hash=sha256:" in text[match.start() : end], match.group("name")


def test_requirement_inputs_are_kept_in_sync_with_pyproject() -> None:
    assert _input_requirements("requirements/runtime.in") == _project_requirements()
    assert _input_requirements("requirements/dev.in") == _project_requirements("dev")
    assert _input_requirements("requirements/ml.in") == _project_requirements("ml") | {
        "torch==2.13.0+cpu"
    }
    assert _input_requirements("requirements/sdist-build-tools.in") == {
        "pip==26.1.2",
        "setuptools==83.0.0",
    }


def test_all_dependency_locks_are_complete_and_hash_pinned() -> None:
    for path in (
        "requirements/lock-tools.lock",
        "requirements/sdist-build-tools.lock",
        "requirements/runtime.lock",
        "requirements/dev.lock",
        "requirements/ml.lock",
    ):
        _assert_hashed_lock(path)

    assert "torch==2.13.0+cpu" in _read("requirements/ml.lock")
    assert "https://download.pytorch.org/whl/cpu" in _read("requirements/ml.lock")


def test_dockerfile_uses_pinned_python_and_wheel_only_locks() -> None:
    dockerfile = _read("Dockerfile")

    assert (
        "python:3.11.15-slim-trixie@"
        "sha256:00af38ae2ed311628970782e8a2d7f014d8909dbc63cb97bc0a158187f4db045"
    ) in dockerfile
    assert dockerfile.count("FROM ${PYTHON_BASE_IMAGE}") == 2
    assert dockerfile.count("--require-hashes --only-binary=:all:") == 3
    assert "requirements/sdist-build-tools.lock" in dockerfile
    assert "requirements/sdist-bootstrap.lock" in dockerfile
    assert "--require-hashes --no-deps" in dockerfile
    assert "--no-build-isolation --no-binary=docopt" in dockerfile
    assert "version('pip') == '24.0'" in dockerfile
    assert "version('setuptools') == '79.0.1'" in dockerfile
    assert "version('pip') == '26.1.2'" in dockerfile
    assert "version('setuptools') == '83.0.0'" in dockerfile
    assert "requirements/runtime.lock requirements/ml.lock" in dockerfile
    assert dockerfile.count("PIP_NO_CACHE_DIR=1") == 2
    assert "/home/app/.cache /home/app/.cache/huggingface" in dockerfile
    assert "apt-get" not in dockerfile
    assert "build-essential" not in dockerfile
    assert "pip install --upgrade" not in dockerfile
    assert "useradd --uid 10001 --gid 10001" in dockerfile
    assert "re.fullmatch(r'[0-9a-f]{40}', value)" in dockerfile
    assert 'org.opencontainers.image.revision="${RELEASE_GIT_SHA}"' in dockerfile
    assert 'org.opencontainers.image.source="${OCI_SOURCE}"' in dockerfile


def test_only_wheelless_runtime_dependency_has_a_separate_hashed_bootstrap() -> None:
    bootstrap = _read("requirements/sdist-bootstrap.lock")
    build_tools = _read("requirements/sdist-build-tools.lock")
    expected_hash = "49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491"

    assert "docopt==0.6.2" in bootstrap
    assert f"--hash=sha256:{expected_hash}" in bootstrap
    assert expected_hash in _read("requirements/runtime.lock")
    assert expected_hash in _read("requirements/dev.lock")
    assert expected_hash in _read("requirements/ml.lock")
    assert bootstrap.count("==") == 1
    assert "pip==26.1.2" in build_tools
    assert "setuptools==83.0.0" in build_tools
    assert len(re.findall(r"(?m)^[A-Za-z0-9_.-]+==", build_tools)) == 2


def test_compose_external_images_are_immutable_linux_amd64_manifests() -> None:
    compose = _read("docker-compose.yml")
    tls = _read("docker-compose.admin-tls.yml")
    production = _read("docker-compose.prod.yml")
    expected = (
        "postgres:16.14-alpine3.24",
        "redis:7.4.9-alpine",
        "qdrant/qdrant:v1.18.3",
        "nginx:1.30.4-alpine",
        "certbot/certbot:v5.7.0",
        "ubuntu/squid:6.6-24.04_edge",
        "haproxy:3.4.2-alpine",
    )
    combined = f"{compose}\n{tls}\n{production}"

    assert combined.count("platform: linux/amd64") >= len(expected)
    for image in expected:
        line = next(line for line in combined.splitlines() if f"image: {image}@" in line)
        assert SHA256_REF.search(line)


def test_production_images_and_labels_are_tied_to_required_release_sha() -> None:
    compose = _read("docker-compose.prod.yml")

    assert "RELEASE_GIT_SHA:?" in compose
    assert compose.count("rosmol-ai-bot-app:${RELEASE_GIT_SHA:?") == 3
    assert compose.count("rosmol-ai-bot-ml:${RELEASE_GIT_SHA:?") == 5
    assert compose.count("platform: linux/amd64") >= 7
    assert "PYTHON_BASE_IMAGE: python:3.11.15-slim-trixie@sha256:" in compose
    assert ":latest" not in compose


def test_lock_generator_is_pinned_and_isolated() -> None:
    compose = _read("docker-compose.lock.yml")
    tool_input = _read("requirements/lock-tools.in")

    assert "python:3.11.15-slim-trixie@sha256:" in compose
    assert tool_input.strip().endswith("pip-tools==7.6.0")
    assert "requirements/lock-tools.lock" in compose
    assert "requirements/sdist-build-tools.lock" in compose
    assert "--require-hashes --only-binary=:all:" in compose
    assert compose.count("--generate-hashes --resolver=backtracking") == 4
    assert compose.count("--output-file=requirements/") == 4
    assert "--extra-index-url=https://download.pytorch.org/whl/cpu" in compose
    assert "platform: linux/amd64" in compose
    assert "read_only: true" in compose
    assert "cap_drop: [ALL]" in compose
    assert "no-new-privileges:true" in compose


def test_docker_context_defence_in_depth_excludes_build_and_key_material() -> None:
    rules = {
        line.strip()
        for line in _read(".dockerignore").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    assert "!.env.example" not in rules
    assert {
        ".cache/",
        "**/.cache/",
        "build/",
        "**/build/",
        "dist/",
        "**/dist/",
        "models/",
        "**/models/",
        "*.egg-info/",
        "**/*.egg-info/",
        "*.key",
        "*.pem",
        "*.p12",
        "*.pfx",
        "*.backup",
        "*.dump",
        "**/.aws/",
        "**/.azure/",
        "**/.config/gcloud/",
        "**/.kube/",
    } <= rules


def test_python_stdlib_healthchecks_keep_runtime_image_package_free() -> None:
    compose = "\n".join(
        _read(path)
        for path in ("docker-compose.yml", "docker-compose.ml.yml", "docker-compose.prod.yml")
    )
    assert compose.count("urllib.request.urlopen") == 4
    assert "curl -fsS http://127.0.0.1:8000" not in compose


def test_recovery_runbook_pins_history_secret_sbom_and_cve_scanners() -> None:
    runbook = _read("docs/recovery_test_production_runbook_20260720.md")

    assert (
        "zricethezav/gitleaks:v8.28.0@"
        "sha256:bf00b5e039f0fad4b32935dc5ec1e358f227ccd097bcb64b971f0331072fe2ae"
    ) in runbook
    assert (
        "aquasec/trivy:0.64.1@"
        "sha256:de90a656e79b175a294abe85cb8b99670fab83ebf339cccd163e6f584846809a"
    ) in runbook
    for pinned_image in (
        "postgres:16.14-alpine3.24@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777",
        "redis:7.4.9-alpine@sha256:b1addbe72465a718643cff9e60a58e6df1841e29d6d7d60c9a85d8d72f08d1a7",
        "qdrant/qdrant:v1.18.3@sha256:0bd98fa7977f1e75694779359ca4e212822e5a71334e28421182f72f209d5286",
        "nginx:1.30.4-alpine@sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46",
        "certbot/certbot:v5.7.0@sha256:34ee91d2f43008eb78a007d22f23ed4b2eaa9a454cb27ca2c042b49527a695b4",
        "ubuntu/squid:6.6-24.04_edge@sha256:94f844158e12b52f51b4ae996515e37e8fb3e8d85e1c86caba1a297376e4ec4f",
        "haproxy:3.4.2-alpine@sha256:0878b11eb64c433be1b0f578a584b8aca12f6caaa64c8f239b8b556c0dd5eeeb",
    ):
        assert pinned_image in runbook
    assert 'for image in "${production_images[@]}"; do' in runbook
    assert "sed 's/[^A-Za-z0-9._-]/_/g'" in runbook
    assert "detect --source=/repo --redact" in runbook
    assert "VulnerabilityDB.UpdatedAt" in runbook
    assert "image --skip-db-update --scanners vuln --severity CRITICAL --exit-code 1" in runbook
    assert "image --skip-db-update --scanners secret --exit-code 1" in runbook
    assert "--ignorefile /repo/security/trivy-app-ignore.yaml --show-suppressed" in runbook
    assert "--ignorefile /repo/security/trivy-postgres-ignore.yaml --show-suppressed" in runbook
    assert "--ignorefile /repo/security/trivy-qdrant-ignore.yaml --show-suppressed" in runbook
    assert "TRIVY_EXCEPTION_REVIEW_DEADLINE='2026-07-27'" in runbook
    assert "render-egress-proxy --env-file .env.production" in runbook
    assert '"$RUNTIME_EGRESS_PROXY_IMAGE" -k parse' in runbook
    assert '"$EDGE_RELAY_IMAGE" -c -f' in runbook
    assert "runtime_https_egress_gate=passed" in runbook


def test_every_recovery_runbook_bash_block_is_fail_closed() -> None:
    runbook = _read("docs/recovery_test_production_runbook_20260720.md")

    bash_blocks = runbook.split("```bash\n")[1:]
    assert bash_blocks
    assert all(block.startswith("set -Eeuo pipefail\n") for block in bash_blocks)


def test_recovery_runbook_uses_supported_no_pull_runtime_commands() -> None:
    runbook = _read("docs/recovery_test_production_runbook_20260720.md")

    assert "run --rm --no-build" not in runbook
    assert "run --rm --pull never migrate" in runbook
    assert "run --rm --no-deps --pull never model-prefetch" in runbook
    assert "up -d --no-build app app-ml nginx edge-relay" in runbook
    assert "from src.config import get_settings" in runbook
    assert "settings = get_settings()" in runbook
    assert "-X POST -H 'Content-Type: application/json'" in runbook
    assert ".dockerignore Dockerfile requirements deploy/huggingface_models.lock.json" in runbook
